version: '3'

networks:
  front:
  back:

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      front:
        aliases:
          - redis
      back:
        aliases:
          - redis

  postgres:
    image: postgres
    ports:
      - "25432:5432"
    environment:
      LC_ALL: C.UTF-8
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      back:
      front:
        aliases:
          - postgres
        aliases:
          - postgres
